/**
 * Glass Command Palette — static command registry (Task #66).
 * Built-in Glass commands surfaced in the ⌘⇧G Command Palette (not ⌘⇧P Powers Menu).
 *
 * No Electron or React imports — safe for src/shared/.
 * Each entry maps to a GlassCommandItem at assembly time. The `send-glass-command`
 * payloads are GlassCommand objects; only types that exist in the GlassCommand
 * union (see ipc.ts) are used here.
 */

import type { GlassCommandRegistryEntry } from "./paletteTypes.ts";

export const PALETTE_COMMAND_REGISTRY: GlassCommandRegistryEntry[] = [
  {
    commandId: "context-ask",
    title: "Ask with Screen Context",
    subtitle: "Snapshot window + terminal context, then focus the command bar",
    icon: "◎",
    section: "ask",
    contextTags: ["always-top"],
    keywords: ["context", "ask", "screen", "window", "snapshot", "capture"],
    action: { kind: "send-glass-command", payload: { type: "glass-context-ask" } },
  },
  {
    commandId: "ask-glass",
    title: "Ask Glass",
    subtitle: "Open the command bar and ask anything",
    icon: "⬡",
    shortcutHint: "↵",
    section: "ask",
    contextTags: ["always-top"],
    keywords: ["ask", "chat", "question", "prompt", "iivo", "command bar", "query"],
    action: { kind: "prefill-command-bar", payload: "" },
  },
  {
    commandId: "open-answer-panel",
    title: "Answer Panel",
    subtitle: "Open the formatted side panel for your last command-bar answer",
    icon: "▤",
    section: "ask",
    contextTags: ["always-top"],
    keywords: [
      "answer",
      "panel",
      "response",
      "formatted",
      "markdown",
      "side",
      "last",
      "reopen",
      "show",
      "open",
    ],
    action: { kind: "send-glass-command", payload: { type: "open-answer-panel" } },
  },
  {
    commandId: "fix-terminal-error",
    title: "Fix Last Terminal Error",
    subtitle: "Let Claude repair the last failed command",
    icon: "↗",
    section: "terminal",
    contextTags: ["terminal-error"],
    keywords: ["fix", "error", "repair", "terminal", "broken", "failed", "command"],
    action: { kind: "send-glass-command", payload: { type: "terminal-fix-last" } },
  },
  {
    commandId: "explain-terminal",
    title: "Explain Last Command",
    subtitle: "Get a plain-English explanation of what just ran",
    icon: "?",
    section: "terminal",
    contextTags: ["terminal"],
    keywords: ["explain", "what", "terminal", "command", "output", "understand"],
    action: { kind: "send-glass-command", payload: { type: "terminal-explain-last" } },
  },
  {
    commandId: "nl-to-shell",
    title: "Natural Language → Shell",
    subtitle: "Describe a task; Glass writes the shell command",
    icon: "⌘",
    section: "terminal",
    contextTags: ["terminal"],
    keywords: ["natural language", "shell", "command", "convert", "generate", "translate", "nl"],
    action: { kind: "send-glass-command", payload: { type: "terminal-nl-focus" } },
  },
  {
    commandId: "extract-start",
    title: "Start Extract & Build Mode",
    subtitle: "Capture audio and turn ideas into build prompts",
    icon: "⬡",
    section: "extract",
    contextTags: ["always-top"],
    keywords: ["extract", "build", "start", "capture", "transcript", "mode", "prompt"],
    action: { kind: "send-glass-command", payload: { type: "extract-mode-start" } },
  },
  {
    commandId: "extract-stop",
    title: "Stop Extract & Build Mode",
    subtitle: "End audio capture and generate the build prompt",
    icon: "⬡",
    section: "extract",
    contextTags: ["extract-active"],
    keywords: ["extract", "build", "stop", "end", "finish", "mode", "generate"],
    action: { kind: "send-glass-command", payload: { type: "extract-mode-stop" } },
  },
  {
    commandId: "open-prompts",
    title: "Open Prompt Library",
    subtitle: "Browse and run saved power prompts",
    icon: "✦",
    section: "builder",
    contextTags: ["always-top"],
    keywords: ["prompt", "library", "saved", "templates", "power prompt", "open"],
    action: { kind: "open-builder-tab", payload: "prompts" },
  },
  {
    commandId: "open-keys",
    title: "Open API Key Manager",
    subtitle: "View, add, and copy stored API keys",
    icon: "🔑",
    section: "builder",
    contextTags: ["always-top"],
    keywords: ["api", "key", "keys", "manager", "secret", "token", "credentials", "open"],
    action: { kind: "open-builder-tab", payload: "keys" },
  },
  {
    commandId: "open-spend",
    title: "Open Spend Tracker",
    subtitle: "See live AI provider spend across services",
    icon: "💸",
    section: "builder",
    contextTags: ["always-top"],
    keywords: ["spend", "cost", "billing", "usage", "money", "tracker", "budget", "open"],
    action: { kind: "open-builder-tab", payload: "spend" },
  },
  {
    commandId: "open-terminal",
    title: "Open Terminal",
    subtitle: "Launch the built-in Glass terminal",
    icon: "⬛",
    section: "terminal",
    contextTags: ["always-top"],
    keywords: ["terminal", "shell", "console", "open", "command line", "pty"],
    action: { kind: "open-terminal" },
  },
  {
    commandId: "clear-terminal",
    title: "Clear Terminal",
    subtitle: "Wipe the current terminal scrollback",
    icon: "✕",
    section: "terminal",
    contextTags: ["terminal"],
    keywords: ["clear", "clean", "terminal", "wipe", "reset", "scrollback"],
    action: { kind: "send-glass-command", payload: { type: "clear-terminal" } },
  },
  {
    commandId: "explain-clipboard",
    title: "Explain Clipboard",
    subtitle: "Have Glass explain whatever you just copied",
    icon: "⧉",
    section: "clipboard",
    contextTags: ["has-clipboard"],
    keywords: ["clipboard", "explain", "paste", "copied", "what is", "understand"],
    action: { kind: "send-glass-command", payload: { type: "explain-clipboard" } },
  },
];
