/**
 * Command feed entries surfaced as floating overlay response cards.
 * Shared, no Electron imports.
 */

export type GlassCommandFeedKind =
  | "command"
  | "looking"
  | "thinking"
  | "response"
  | "capture"
  | "transcript"
  | "error"
  | "moment"
  /** Glass terminal detected a non-zero exit code — shows fix suggestion + Fix it button */
  | "terminal-fix"
  /** /run <command> executed from the command bar — card is a handle for ShellOutputCard */
  | "shell"
  /** Build error detected in-stream from the Glass dock terminal */
  | "build-error"
  /** Design-to-code capture card — shows screenshot thumbnail + 4 quick-action buttons */
  | "design-capture"
  /** Audio/video session produced a build plan — shows "Build from video" action button */
  | "build-from-audio";

export interface GlassCommandFeedItem {
  id: string;
  kind: GlassCommandFeedKind;
  title: string;
  body: string;
  at: string;
  pinned?: boolean;
  runId?: string;
  contextId?: string;
  prompt?: string;
  fullBody?: string;
  /** Listen mode — ties card to a moment; only one listen card visible at a time. */
  listenMomentId?: string;
  // ── Terminal auto-fix fields ──────────────────────────────────────────────
  /** The PTY session that produced the error (for terminal-fix cards). */
  termId?: string;
  /** The exact corrected command to type when "Fix it" is clicked. */
  fixCommand?: string;
  /** The original failing command (shown as context in the card). */
  failedCommand?: string;
  // ── /run shell output fields ──────────────────────────────────────────────
  /** Key into GlassState.shellOutputs — used by ShellOutputCard to find streaming data. */
  shellOutputId?: string;
  // ── Fix injection fields ──────────────────────────────────────────────────
  /**
   * Absolute path to the file that was open in the editor when this response
   * was generated. Set only when ⌘⇧G captured a code context with a resolved
   * filePath. Used by the "Apply to file" button in the overlay.
   */
  codeFilePath?: string;
  // ── Build monitor fields ──────────────────────────────────────────────────
  /** Raw error text captured from the build output (for build-error cards). */
  errorText?: string;
  /** File paths referenced in the build error (for "Fix with AI" context). */
  errorFilePaths?: string[];
  // ── Design-to-code fields (#163) ─────────────────────────────────────────
  /** data: URL screenshot thumbnail for design-capture cards. */
  designImageDataUrl?: string;
  /** Filename of the detected editor file shown on the design card. */
  designDetectedFileName?: string;
  /**
   * Set on response cards generated by design-to-code (#163-F).
   * Tells the FeedCard which action produced this result so it can offer
   * the right "Save component" extension when no codeFilePath is available.
   */
  designAction?: import("./designToCode.ts").DesignToCodeAction;
  /**
   * The stack setting that was active when this design-to-code response was
   * generated. Used by "Save component" to write the correct file extension
   * even if the user changes the stack picker after generation.
   */
  designStack?: import("./designToCode.ts").DesignStack;
  /**
   * Id of the design-capture feed item that triggered this response.
   * Used by the "Refine" flow — `design-generate` is keyed on the capture id,
   * not the response id, so the renderer needs this to send the right feedItemId.
   */
  designCaptureId?: string;
  // ── Build-from-audio fields ───────────────────────────────────────────────
  /** Pre-formatted Coder prompt from audio intent extraction (for build-from-audio cards). */
  audioBuildPrompt?: string;
}

export const MAX_COMMAND_FEED_ITEMS = 12;

export const COMMAND_FEED_TITLES: Record<GlassCommandFeedKind, string> = {
  command: "You asked",
  looking: "IIVO is looking",
  thinking: "IIVO is thinking",
  response: "IIVO",
  capture: "Capture",
  transcript: "Transcript",
  error: "Warning",
  moment: "Saved moment",
  "terminal-fix": "Glass Terminal",
  shell: "Running",
  "build-error": "Build error",
  "design-capture": "Design to Code",
  "build-from-audio": "Build from video",
};

let feedSeq = 0;

export function createCommandFeedItem(
  kind: GlassCommandFeedKind,
  body: string,
  opts: {
    title?: string;
    pinned?: boolean;
    at?: string;
    runId?: string;
    contextId?: string;
    prompt?: string;
    fullBody?: string;
    listenMomentId?: string;
    termId?: string;
    fixCommand?: string;
    failedCommand?: string;
    shellOutputId?: string;
    codeFilePath?: string;
    errorText?: string;
    errorFilePaths?: string[];
    designImageDataUrl?: string;
    designDetectedFileName?: string;
    designAction?: import("./designToCode.ts").DesignToCodeAction;
    designStack?: import("./designToCode.ts").DesignStack;
    designCaptureId?: string;
    audioBuildPrompt?: string;
  } = {},
): GlassCommandFeedItem {
  feedSeq += 1;
  return {
    id: `feed-${Date.now()}-${feedSeq}`,
    kind,
    title: opts.title ?? COMMAND_FEED_TITLES[kind],
    body,
    at: opts.at ?? new Date().toISOString(),
    pinned: opts.pinned,
    runId: opts.runId,
    contextId: opts.contextId,
    prompt: opts.prompt,
    fullBody: opts.fullBody,
    listenMomentId: opts.listenMomentId,
    termId: opts.termId,
    fixCommand: opts.fixCommand,
    failedCommand: opts.failedCommand,
    shellOutputId: opts.shellOutputId,
    codeFilePath: opts.codeFilePath,
    errorText: opts.errorText,
    errorFilePaths: opts.errorFilePaths,
    designImageDataUrl: opts.designImageDataUrl,
    designDetectedFileName: opts.designDetectedFileName,
    designAction: opts.designAction,
    designStack: opts.designStack,
    designCaptureId: opts.designCaptureId,
    audioBuildPrompt: opts.audioBuildPrompt,
  };
}

export function appendCommandFeedItem(
  feed: GlassCommandFeedItem[],
  item: GlassCommandFeedItem,
  max = MAX_COMMAND_FEED_ITEMS,
): GlassCommandFeedItem[] {
  return [...feed, item].slice(-max);
}

export const OVERLAY_CHAT_FEED_KINDS: GlassCommandFeedKind[] = [
  "thinking",
  "looking",
  "response",
  "error",
];

export function isOverlayChatFeedKind(kind: GlassCommandFeedKind): boolean {
  return OVERLAY_CHAT_FEED_KINDS.includes(kind);
}

/** Latest overlay chat card (skips standalone "command" rows). */
export function pickOverlayChatFeedItem(
  feed: GlassCommandFeedItem[],
): GlassCommandFeedItem | null {
  for (let i = feed.length - 1; i >= 0; i -= 1) {
    const item = feed[i];
    if (isOverlayChatFeedKind(item.kind)) return item;
  }
  return null;
}

export function resolveOverlayChatPrompt(
  item: GlassCommandFeedItem,
  feed: GlassCommandFeedItem[],
): string | undefined {
  const direct = item.prompt?.trim();
  if (direct) return direct;
  const idx = feed.findIndex((f) => f.id === item.id);
  if (idx < 0) return undefined;
  for (let i = idx - 1; i >= 0; i -= 1) {
    if (feed[i].kind === "command") {
      const body = feed[i].body.trim();
      if (body) return body;
    }
  }
  return undefined;
}
